package com.webares.webares;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

public class DATA_Web {
    // https://nuclearesgame.blogspot.com/2023/11/webserver.html
    public static final String BASE_URL = "http://192.168.1.12:8785/?Variable=";
    public static final ArrayList<String> VARIABLES = new ArrayList<>(Arrays.asList(
            "TIME",
            "RODS_POS_ACTUAL",
            "COOLANT_CORE_QUANTITY_IN_VESSEL",
            "CORE_STATE",
            "CORE_TEMP",
            "CORE_PRESSURE",
            "CORE_INTEGRITY",
            "CORE_CRITICAL_MASS_REACHED",
            "CORE_STEAM_PRESENT",
            "CORE_HIGH_STEAM_PRESENT",
            "COOLANT_CORE_CIRCULATION_PUMP_0_STATUS",
            "COOLANT_CORE_CIRCULATION_PUMP_1_STATUS",
            "COOLANT_CORE_CIRCULATION_PUMP_2_STATUS",
            "COOLANT_CORE_CIRCULATION_PUMP_0_DRY_STATUS",
            "COOLANT_CORE_CIRCULATION_PUMP_1_DRY_STATUS",
            "COOLANT_CORE_CIRCULATION_PUMP_2_DRY_STATUS",
            "COOLANT_CORE_CIRCULATION_PUMP_0_SPEED",
            "COOLANT_CORE_CIRCULATION_PUMP_1_SPEED",
            "COOLANT_CORE_CIRCULATION_PUMP_2_SPEED",
            "COOLANT_SEC_CIRCULATION_PUMP_0_STATUS",
            "COOLANT_SEC_CIRCULATION_PUMP_1_STATUS",
            "COOLANT_SEC_CIRCULATION_PUMP_2_STATUS",
            "COOLANT_SEC_CIRCULATION_PUMP_0_DRY_STATUS",
            "COOLANT_SEC_CIRCULATION_PUMP_1_DRY_STATUS",
            "COOLANT_SEC_CIRCULATION_PUMP_2_DRY_STATUS",
            "COOLANT_SEC_CIRCULATION_PUMP_0_SPEED",
            "COOLANT_SEC_CIRCULATION_PUMP_1_SPEED",
            "COOLANT_SEC_CIRCULATION_PUMP_2_SPEED",
            "COOLANT_SEC_0_PRESSURE",
            "COOLANT_SEC_1_PRESSURE",
            "COOLANT_SEC_2_PRESSURE",
            "COOLANT_SEC_0_VOLUME",
            "COOLANT_SEC_1_VOLUME",
            "COOLANT_SEC_2_VOLUME",
            "CONDENSER_CIRCULATION_PUMP_SPEED",
            "CONDENSER_VOLUME",
            "MSCV_0_OPENING_ACTUAL",
            "MSCV_1_OPENING_ACTUAL",
            "MSCV_2_OPENING_ACTUAL",
            "STEAM_TURBINE_0_TEMPERATURE",
            "STEAM_TURBINE_1_TEMPERATURE",
            "STEAM_TURBINE_2_TEMPERATURE",
            "STEAM_TURBINE_0_PRESSURE",
            "STEAM_TURBINE_1_PRESSURE",
            "STEAM_TURBINE_2_PRESSURE",
            "STEAM_TURBINE_0_BYPASS_ACTUAL",
            "STEAM_TURBINE_1_BYPASS_ACTUAL",
            "STEAM_TURBINE_2_BYPASS_ACTUAL",
            "STEAM_TURBINE_0_RPM",
            "STEAM_TURBINE_1_RPM",
            "STEAM_TURBINE_2_RPM",
            "GENERATOR_0_KW",
            "GENERATOR_1_KW",
            "GENERATOR_2_KW",
            "GENERATOR_0_A",
            "GENERATOR_1_A",
            "GENERATOR_2_A",
            "GENERATOR_0_V",
            "GENERATOR_1_V",
            "GENERATOR_2_V",
            "GENERATOR_0_HERTZ",
            "GENERATOR_1_HERTZ",
            "GENERATOR_2_HERTZ",
            "GENERATOR_0_BREAKER",
            "GENERATOR_1_BREAKER",
            "GENERATOR_2_BREAKER"

    ));
    public static Map<String, String> table = new HashMap<>(Map.ofEntries(
            Map.entry( "TIME","0:00"),
            Map.entry("RODS_POS_ACTUAL", "100"),
            Map.entry("COOLANT_CORE_QUANTITY_IN_VESSEL", "120000.0"),
            Map.entry("CORE_STATE","REACTIVO"),
            Map.entry("CORE_TEMP","0"),
            Map.entry("CORE_PRESSURE","0"),
            Map.entry("CORE_INTEGRITY","0"),
            Map.entry("CORE_CRITICAL_MASS_REACHED","FALSE"),
            Map.entry("CORE_STEAM_PRESENT","FALSE"),
            Map.entry("CORE_HIGH_STEAM_PRESENT","FALSE"),
            Map.entry("COOLANT_CORE_CIRCULATION_PUMP_0_STATUS","1"),
            Map.entry("COOLANT_CORE_CIRCULATION_PUMP_1_STATUS","1"),
            Map.entry("COOLANT_CORE_CIRCULATION_PUMP_2_STATUS","1"),
            Map.entry("COOLANT_CORE_CIRCULATION_PUMP_0_DRY_STATUS","4"),
            Map.entry("COOLANT_CORE_CIRCULATION_PUMP_1_DRY_STATUS","4"),
            Map.entry("COOLANT_CORE_CIRCULATION_PUMP_2_DRY_STATUS","4"),
            Map.entry("COOLANT_CORE_CIRCULATION_PUMP_0_SPEED", "100"),
            Map.entry("COOLANT_CORE_CIRCULATION_PUMP_1_SPEED", "100"),
            Map.entry("COOLANT_CORE_CIRCULATION_PUMP_2_SPEED", "100"),
            Map.entry("COOLANT_SEC_CIRCULATION_PUMP_0_STATUS","1"),
            Map.entry("COOLANT_SEC_CIRCULATION_PUMP_1_STATUS","1"),
            Map.entry("COOLANT_SEC_CIRCULATION_PUMP_2_STATUS","1"),
            Map.entry("COOLANT_SEC_CIRCULATION_PUMP_0_DRY_STATUS","4"),
            Map.entry("COOLANT_SEC_CIRCULATION_PUMP_1_DRY_STATUS","4"),
            Map.entry("COOLANT_SEC_CIRCULATION_PUMP_2_DRY_STATUS","4"),
            Map.entry("COOLANT_SEC_CIRCULATION_PUMP_0_SPEED", "100"),
            Map.entry("COOLANT_SEC_CIRCULATION_PUMP_1_SPEED", "100"),
            Map.entry("COOLANT_SEC_CIRCULATION_PUMP_2_SPEED", "100"),
            Map.entry("COOLANT_SEC_0_PRESSURE", "120"),
            Map.entry("COOLANT_SEC_1_PRESSURE", "120"),
            Map.entry("COOLANT_SEC_2_PRESSURE", "120"),
            Map.entry("COOLANT_SEC_0_VOLUME", "60000.0"),
            Map.entry("COOLANT_SEC_1_VOLUME", "60000.0"),
            Map.entry("COOLANT_SEC_2_VOLUME", "60000.0"),
            Map.entry("CONDENSER_CIRCULATION_PUMP_SPEED", "1"),
            Map.entry("CONDENSER_VOLUME", "360000.0"),
            Map.entry("MSCV_0_OPENING_ACTUAL", "1"),
            Map.entry("MSCV_1_OPENING_ACTUAL", "1"),
            Map.entry("MSCV_2_OPENING_ACTUAL", "1"),
            Map.entry("STEAM_TURBINE_0_TEMPERATURE","0.00"),
            Map.entry("STEAM_TURBINE_1_TEMPERATURE","0.00"),
            Map.entry("STEAM_TURBINE_2_TEMPERATURE","0.00"),
            Map.entry("STEAM_TURBINE_0_PRESSURE", "120"),
            Map.entry("STEAM_TURBINE_1_PRESSURE", "120"),
            Map.entry("STEAM_TURBINE_2_PRESSURE", "120"),
            Map.entry("STEAM_TURBINE_0_BYPASS_ACTUAL", "1"),
            Map.entry("STEAM_TURBINE_1_BYPASS_ACTUAL", "1"),
            Map.entry("STEAM_TURBINE_2_BYPASS_ACTUAL", "1"),
            Map.entry("STEAM_TURBINE_0_RPM", "3060"),
            Map.entry("STEAM_TURBINE_1_RPM", "3060"),
            Map.entry("STEAM_TURBINE_2_RPM", "3060"),
            Map.entry("GENERATOR_0_KW","0.00"),
            Map.entry("GENERATOR_1_KW","0.00"),
            Map.entry("GENERATOR_2_KW","0.00"),
            Map.entry("GENERATOR_0_A","0.00"),
            Map.entry("GENERATOR_1_A","0.00"),
            Map.entry("GENERATOR_2_A","0.00"),
            Map.entry("GENERATOR_0_V","0.00"),
            Map.entry("GENERATOR_1_V","0.00"),
            Map.entry("GENERATOR_2_V","0.00"),
            Map.entry("GENERATOR_0_HERTZ","0.00"),
            Map.entry("GENERATOR_1_HERTZ","0.00"),
            Map.entry("GENERATOR_2_HERTZ","0.00"),
            Map.entry("GENERATOR_0_BREAKER","FALSE"),
            Map.entry("GENERATOR_1_BREAKER","FALSE"),
            Map.entry("GENERATOR_2_BREAKER","FALSE")
    ));
}
